# Generated by Django 4.0 on 2022-08-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_1', models.IntegerField()),
                ('num_2', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
    ]
