# Generated by Django 4.0 on 2022-08-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='sym',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
