# Generated by Django 4.0 on 2022-08-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_calculator_sym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='num_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='num_2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='result',
            field=models.FloatField(),
        ),
    ]
